# Generated by Django 6.1.1 on 2026-09-22 17:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSEO',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('focus_keyword', models.CharField(blank=True, default='', max_length=255)),
                ('seo_title', models.CharField(blank=True, default='', max_length=255)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('canonical_url', models.URLField(blank=True, default='', max_length=500)),
                ('robots_index', models.BooleanField(default=True, help_text='Allow search engines to index this page')),
                ('robots_follow', models.BooleanField(default=True, help_text='Allow search engines to follow links on this page')),
                ('og_title', models.CharField(blank=True, default='', max_length=255)),
                ('og_description', models.TextField(blank=True, default='')),
                ('og_image', models.URLField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='posts.post')),
            ],
            options={
                'verbose_name': 'Post SEO Configuration',
                'verbose_name_plural': 'Post SEO Configurations',
            },
        ),
    ]
