# Generated by Django 6.1.1 on 2026-09-22 17:53

import apps.media.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.media.models.media_upload_path)),
                ('url', models.URLField(blank=True, help_text='Direct URL if stored on CDN / S3 / R2', max_length=1000)),
                ('filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Size in bytes')),
                ('alt_text', models.CharField(blank=True, default='', max_length=255)),
                ('storage_provider', models.CharField(choices=[('local', 'Local Storage'), ('s3', 'Amazon S3'), ('r2', 'Cloudflare R2')], default='local', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='sites.site')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
