# Generated by Django 6.1.1 on 2026-09-22 17:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        ('sites', '0001_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('content', models.JSONField(blank=True, default=dict, help_text='TipTap editor structured JSON')),
                ('content_html', models.TextField(blank=True, default='', help_text='HTML render for fast SSR rendering')),
                ('excerpt', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('author', models.CharField(blank=True, default='Admin', max_length=150)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='taxonomy.category')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_in_posts', to='media.media')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='sites.site')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='taxonomy.tag')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('site', 'slug')},
            },
        ),
    ]
